// <auto-generated />
using System;
using FoodSave.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSave.Api.Migrations
{
    [DbContext(typeof(FoodSaveDbContext))]
    [Migration("20260707024414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodSave.Api.Models.ConfirmacionRetiro", b =>
                {
                    b.Property<int>("ConfirmacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfirmacionId"));

                    b.Property<bool>("ConfirmadoPorConsumidor")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmadoPorEstablecimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("ConfirmacionId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("ConfirmacionesRetiro");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Establecimiento", b =>
                {
                    b.Property<int>("EstablecimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstablecimientoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstablecimientoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("FoodSave.Api.Models.OfertaAlimento", b =>
                {
                    b.Property<int>("OfertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfertaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DisponibleHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstablecimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfertaId");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("ConsumidorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraRetiro")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("ConsumidorId");

                    b.HasIndex("OfertaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Nombre = "Establecimiento"
                        },
                        new
                        {
                            RolId = 2,
                            Nombre = "Consumidor"
                        });
                });

            modelBuilder.Entity("FoodSave.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FoodSave.Api.Models.ConfirmacionRetiro", b =>
                {
                    b.HasOne("FoodSave.Api.Models.Reserva", "Reserva")
                        .WithOne("ConfirmacionRetiro")
                        .HasForeignKey("FoodSave.Api.Models.ConfirmacionRetiro", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Establecimiento", b =>
                {
                    b.HasOne("FoodSave.Api.Models.Usuario", "Usuario")
                        .WithOne("Establecimiento")
                        .HasForeignKey("FoodSave.Api.Models.Establecimiento", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FoodSave.Api.Models.OfertaAlimento", b =>
                {
                    b.HasOne("FoodSave.Api.Models.Establecimiento", "Establecimiento")
                        .WithMany("Ofertas")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Reserva", b =>
                {
                    b.HasOne("FoodSave.Api.Models.Usuario", "Consumidor")
                        .WithMany("Reservas")
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSave.Api.Models.OfertaAlimento", "Oferta")
                        .WithMany("Reservas")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Usuario", b =>
                {
                    b.HasOne("FoodSave.Api.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Establecimiento", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("FoodSave.Api.Models.OfertaAlimento", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Reserva", b =>
                {
                    b.Navigation("ConfirmacionRetiro");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FoodSave.Api.Models.Usuario", b =>
                {
                    b.Navigation("Establecimiento");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
